root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "gen"]
  include_ext = ["go"]
  kill_delay = "0s"

[misc]
  clean_on_exit = true